version: '3'
services:
  web:
    build: web/ # For development only to push to dockerhub
    image: helpbuttons/helpbuttons-web:main
    entrypoint: yarn dev # For development 
    ports:
      - "3000:3000"
    depends_on:
      - api
   volumes: # For development only
     - ./env.web:/app/.env:ro
     - ./web/src:/app/src/:ro
    networks:
      - web
      - api

  api:
    build: api/ # For development only to push to dockerhub
    image: helpbuttons/helpbuttons-api:main
    entrypoint: yarn dev # For development 
    volumes:
      - ./config/:/app/config/:rw
      - ./uploads:/app/uploads
      - ./api/src:/app/src/:ro # for development only
    depends_on:
      - db
    networks:
      - api
      - db

  db:
    image: postgis/postgis:13-master
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - /live/storage/helpbuttons/db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db

networks:
  web:
    external:
      name: web
  api:
  db:
