version: '3.4'
services:
  web:
    build: web/
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: api/
    depends_on:
      - db
#    ports:
#      - "3001:3001"

  db:
    image: postgis/postgis:13-master
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - env.db
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  graphhopper:
    image: israelhikingmap/graphhopper:6.2
    ports:
      - "8989:8989"
    volumes:
      - ghdata:/data:rw
      - type: bind
        source: ./graphhopper/gh-config.yml
        target: /data/gh-config.yml
      - type: bind
        source: ./graphhopper/portugal-latest.osm.pbf
        target: /graphhopper/portugal-latest.osm.pbf
    ports:
      - 8989:8989
    entrypoint: ./graphhopper.sh --host 0.0.0.0 -i portugal-latest.osm.pbf -o /data/default-gh/ -c /data/gh-config.yml
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g -XX:MaxPermSize=4096M

volumes:
  ghdata:
    driver: local

# deploy:
#   resources:
#     limits:
#       memory: 4096m