name: ci-test
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: "lint"
        run: |
         yarn
         yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: "build"
        run: |
         cp .env.sample .env
         yarn
         yarn build
